DEFINE_BITFIELD(obj_flags_nova, list(
	"ANVIL_REPAIR" = ANVIL_REPAIR,
	"ERP_ITEM" = ERP_ITEM,
	"NO_CRYO_FREEZE" = NO_CRYO_FREEZE,
))

DEFINE_BITFIELD(chemical_flags_nova, list(
	"REAGENT_BLOOD_REGENERATING" = REAGENT_BLOOD_REGENERATING,
	"REAGENT_NEUROWARE" = REAGENT_NEUROWARE,
))
