/datum/sprite_accessory/clothing
	/// Set to TRUE if this icon has its own custom icon for digi (as opposed to the GAGS autogenerated ones)
	var/has_custom_digi_sprite
	/// Whether this underwear includes a top (Because gender = FEMALE doesn't actually apply here.). Hides breasts, nothing more.
	var/hides_breasts = FALSE
