//список с абсолютно всеми экстрактами в билде как же они круты

GLOBAL_LIST_INIT(slime_extract_random, list(
	// ========== БАЗОВЫЕ ЭКСТРАКТЫ (ВЕСА 100-60) ==========
	// Самые распространённые цвета (вес 100)
	/obj/item/slime_extract/grey = 100,
	/obj/item/slime_extract/orange = 100,
	/obj/item/slime_extract/purple = 100,
	/obj/item/slime_extract/blue = 100,
	/obj/item/slime_extract/metal = 100,
	/obj/item/slime_extract/yellow = 100,
	// Средние по редкости цвета (вес 85)
	/obj/item/slime_extract/darkpurple = 85,
	/obj/item/slime_extract/darkblue = 85,
	/obj/item/slime_extract/silver = 85,
	/obj/item/slime_extract/red = 85,
	/obj/item/slime_extract/green = 85,
	/obj/item/slime_extract/pink = 85,
	// Редкие цвета (вес 70)
	/obj/item/slime_extract/lightpink = 70,
	/obj/item/slime_extract/black = 70,
	/obj/item/slime_extract/oil = 70,
	/obj/item/slime_extract/adamantine = 70,
	/obj/item/slime_extract/pyrite = 70,
	/obj/item/slime_extract/cerulean = 70,
	/obj/item/slime_extract/sepia = 70,
	// Очень редкие цвета (вес 60)
	/obj/item/slime_extract/bluespace = 60,
	/obj/item/slime_extract/gold = 60,
	/obj/item/slime_extract/rainbow = 30,

	// ========== CROSSBREEDS: BURNING (ВЕСА 45-10) ==========
	/obj/item/slimecross/burning/grey = 45,
	/obj/item/slimecross/burning/orange = 45,
	/obj/item/slimecross/burning/purple = 42,
	/obj/item/slimecross/burning/blue = 42,
	/obj/item/slimecross/burning/metal = 42,
	/obj/item/slimecross/burning/yellow = 40,
	/obj/item/slimecross/burning/darkpurple = 35,
	/obj/item/slimecross/burning/darkblue = 35,
	/obj/item/slimecross/burning/silver = 35,
	/obj/item/slimecross/burning/red = 32,
	/obj/item/slimecross/burning/green = 32,
	/obj/item/slimecross/burning/pink = 30,
	/obj/item/slimecross/burning/lightpink = 25,
	/obj/item/slimecross/burning/black = 25,
	/obj/item/slimecross/burning/oil = 25,
	/obj/item/slimecross/burning/adamantine = 22,
	/obj/item/slimecross/burning/pyrite = 22,
	/obj/item/slimecross/burning/cerulean = 22,
	/obj/item/slimecross/burning/sepia = 22,
	/obj/item/slimecross/burning/bluespace = 18,
	/obj/item/slimecross/burning/gold = 15,
	/obj/item/slimecross/burning/rainbow = 10,

	// ========== CROSSBREEDS: CHILLING (ВЕСА 45-10) ==========
	/obj/item/slimecross/chilling/grey = 45,
	/obj/item/slimecross/chilling/orange = 45,
	/obj/item/slimecross/chilling/purple = 42,
	/obj/item/slimecross/chilling/blue = 42,
	/obj/item/slimecross/chilling/metal = 42,
	/obj/item/slimecross/chilling/yellow = 40,
	/obj/item/slimecross/chilling/darkpurple = 35,
	/obj/item/slimecross/chilling/darkblue = 35,
	/obj/item/slimecross/chilling/silver = 35,
	/obj/item/slimecross/chilling/red = 32,
	/obj/item/slimecross/chilling/green = 32,
	/obj/item/slimecross/chilling/pink = 30,
	/obj/item/slimecross/chilling/lightpink = 25,
	/obj/item/slimecross/chilling/black = 25,
	/obj/item/slimecross/chilling/oil = 25,
	/obj/item/slimecross/chilling/adamantine = 22,
	/obj/item/slimecross/chilling/pyrite = 22,
	/obj/item/slimecross/chilling/cerulean = 22,
	/obj/item/slimecross/chilling/sepia = 22,
	/obj/item/slimecross/chilling/bluespace = 18,
	/obj/item/slimecross/chilling/gold = 15,
	/obj/item/slimecross/chilling/rainbow = 10,

	// ========== CROSSBREEDS: CONSUMING (ВЕСА 45-10) ==========
	/obj/item/slimecross/consuming/grey = 45,
	/obj/item/slimecross/consuming/orange = 45,
	/obj/item/slimecross/consuming/purple = 42,
	/obj/item/slimecross/consuming/blue = 42,
	/obj/item/slimecross/consuming/metal = 42,
	/obj/item/slimecross/consuming/yellow = 40,
	/obj/item/slimecross/consuming/darkpurple = 35,
	/obj/item/slimecross/consuming/darkblue = 35,
	/obj/item/slimecross/consuming/silver = 35,
	/obj/item/slimecross/consuming/red = 32,
	/obj/item/slimecross/consuming/green = 32,
	/obj/item/slimecross/consuming/pink = 30,
	/obj/item/slimecross/consuming/lightpink = 25,
	/obj/item/slimecross/consuming/black = 25,
	/obj/item/slimecross/consuming/oil = 25,
	/obj/item/slimecross/consuming/adamantine = 22,
	/obj/item/slimecross/consuming/pyrite = 22,
	/obj/item/slimecross/consuming/cerulean = 22,
	/obj/item/slimecross/consuming/sepia = 22,
	/obj/item/slimecross/consuming/bluespace = 18,
	/obj/item/slimecross/consuming/gold = 15,
	/obj/item/slimecross/consuming/rainbow = 10,

	// ========== CROSSBREEDS: INDUSTRIAL (ВЕСА 45-10) ==========
	/obj/item/slimecross/industrial/grey = 45,
	/obj/item/slimecross/industrial/orange = 45,
	/obj/item/slimecross/industrial/purple = 42,
	/obj/item/slimecross/industrial/blue = 42,
	/obj/item/slimecross/industrial/metal = 42,
	/obj/item/slimecross/industrial/yellow = 40,
	/obj/item/slimecross/industrial/darkpurple = 35,
	/obj/item/slimecross/industrial/darkblue = 35,
	/obj/item/slimecross/industrial/silver = 35,
	/obj/item/slimecross/industrial/red = 32,
	/obj/item/slimecross/industrial/green = 32,
	/obj/item/slimecross/industrial/pink = 30,
	/obj/item/slimecross/industrial/lightpink = 25,
	/obj/item/slimecross/industrial/black = 25,
	/obj/item/slimecross/industrial/oil = 25,
	/obj/item/slimecross/industrial/adamantine = 22,
	/obj/item/slimecross/industrial/pyrite = 22,
	/obj/item/slimecross/industrial/cerulean = 22,
	/obj/item/slimecross/industrial/sepia = 22,
	/obj/item/slimecross/industrial/bluespace = 18,
	/obj/item/slimecross/industrial/gold = 15,
	/obj/item/slimecross/industrial/rainbow = 10,

	// ========== CROSSBREEDS: PRISMATIC (ВЕСА 45-10) ==========
	/obj/item/slimecross/prismatic/grey = 45,
	/obj/item/slimecross/prismatic/orange = 45,
	/obj/item/slimecross/prismatic/purple = 42,
	/obj/item/slimecross/prismatic/blue = 42,
	/obj/item/slimecross/prismatic/metal = 42,
	/obj/item/slimecross/prismatic/yellow = 40,
	/obj/item/slimecross/prismatic/darkpurple = 35,
	/obj/item/slimecross/prismatic/darkblue = 35,
	/obj/item/slimecross/prismatic/silver = 35,
	/obj/item/slimecross/prismatic/red = 32,
	/obj/item/slimecross/prismatic/green = 32,
	/obj/item/slimecross/prismatic/pink = 30,
	/obj/item/slimecross/prismatic/lightpink = 25,
	/obj/item/slimecross/prismatic/black = 25,
	/obj/item/slimecross/prismatic/oil = 25,
	/obj/item/slimecross/prismatic/adamantine = 22,
	/obj/item/slimecross/prismatic/pyrite = 22,
	/obj/item/slimecross/prismatic/cerulean = 22,
	/obj/item/slimecross/prismatic/sepia = 22,
	/obj/item/slimecross/prismatic/bluespace = 18,
	/obj/item/slimecross/prismatic/gold = 15,
	/obj/item/slimecross/prismatic/rainbow = 10,

	// ========== CROSSBREEDS: RECURRING (ВЕСА 45-10) ==========
	/obj/item/slimecross/recurring/grey = 45,
	/obj/item/slimecross/recurring/orange = 45,
	/obj/item/slimecross/recurring/purple = 42,
	/obj/item/slimecross/recurring/blue = 42,
	/obj/item/slimecross/recurring/metal = 42,
	/obj/item/slimecross/recurring/yellow = 40,
	/obj/item/slimecross/recurring/darkpurple = 35,
	/obj/item/slimecross/recurring/darkblue = 35,
	/obj/item/slimecross/recurring/silver = 35,
	/obj/item/slimecross/recurring/red = 32,
	/obj/item/slimecross/recurring/green = 32,
	/obj/item/slimecross/recurring/pink = 30,
	/obj/item/slimecross/recurring/lightpink = 25,
	/obj/item/slimecross/recurring/black = 25,
	/obj/item/slimecross/recurring/oil = 25,
	/obj/item/slimecross/recurring/adamantine = 22,
	/obj/item/slimecross/recurring/pyrite = 22,
	/obj/item/slimecross/recurring/cerulean = 22,
	/obj/item/slimecross/recurring/sepia = 22,
	/obj/item/slimecross/recurring/bluespace = 18,
	/obj/item/slimecross/recurring/gold = 15,
	/obj/item/slimecross/recurring/rainbow = 10,

	// ========== CROSSBREEDS: REGENERATIVE (ВЕСА 45-10) ==========
	/obj/item/slimecross/regenerative/grey = 45,
	/obj/item/slimecross/regenerative/orange = 45,
	/obj/item/slimecross/regenerative/purple = 42,
	/obj/item/slimecross/regenerative/blue = 42,
	/obj/item/slimecross/regenerative/metal = 42,
	/obj/item/slimecross/regenerative/yellow = 40,
	/obj/item/slimecross/regenerative/darkpurple = 35,
	/obj/item/slimecross/regenerative/darkblue = 35,
	/obj/item/slimecross/regenerative/silver = 35,
	/obj/item/slimecross/regenerative/red = 32,
	/obj/item/slimecross/regenerative/green = 32,
	/obj/item/slimecross/regenerative/pink = 30,
	/obj/item/slimecross/regenerative/lightpink = 25,
	/obj/item/slimecross/regenerative/black = 25,
	/obj/item/slimecross/regenerative/oil = 25,
	/obj/item/slimecross/regenerative/adamantine = 22,
	/obj/item/slimecross/regenerative/pyrite = 22,
	/obj/item/slimecross/regenerative/cerulean = 22,
	/obj/item/slimecross/regenerative/sepia = 22,
	/obj/item/slimecross/regenerative/bluespace = 18,
	/obj/item/slimecross/regenerative/gold = 15,
	/obj/item/slimecross/regenerative/rainbow = 10,

	// ========== CROSSBREEDS: SELF-SUSTAINING (ВЕСА 45-10) ==========
	/obj/item/slimecross/selfsustaining/grey = 45,
	/obj/item/slimecross/selfsustaining/orange = 45,
	/obj/item/slimecross/selfsustaining/purple = 42,
	/obj/item/slimecross/selfsustaining/blue = 42,
	/obj/item/slimecross/selfsustaining/metal = 42,
	/obj/item/slimecross/selfsustaining/yellow = 40,
	/obj/item/slimecross/selfsustaining/darkpurple = 35,
	/obj/item/slimecross/selfsustaining/darkblue = 35,
	/obj/item/slimecross/selfsustaining/silver = 35,
	/obj/item/slimecross/selfsustaining/red = 32,
	/obj/item/slimecross/selfsustaining/green = 32,
	/obj/item/slimecross/selfsustaining/pink = 30,
	/obj/item/slimecross/selfsustaining/lightpink = 25,
	/obj/item/slimecross/selfsustaining/black = 25,
	/obj/item/slimecross/selfsustaining/oil = 25,
	/obj/item/slimecross/selfsustaining/adamantine = 22,
	/obj/item/slimecross/selfsustaining/pyrite = 22,
	/obj/item/slimecross/selfsustaining/cerulean = 22,
	/obj/item/slimecross/selfsustaining/sepia = 22,
	/obj/item/slimecross/selfsustaining/bluespace = 18,
	/obj/item/slimecross/selfsustaining/gold = 15,
	/obj/item/slimecross/selfsustaining/rainbow = 10,

	// ========== CROSSBREEDS: STABILIZED (ВЕСА 45-10) ==========
	/obj/item/slimecross/stabilized/grey = 45,
	/obj/item/slimecross/stabilized/orange = 45,
	/obj/item/slimecross/stabilized/purple = 42,
	/obj/item/slimecross/stabilized/blue = 42,
	/obj/item/slimecross/stabilized/metal = 42,
	/obj/item/slimecross/stabilized/yellow = 40,
	/obj/item/slimecross/stabilized/darkpurple = 35,
	/obj/item/slimecross/stabilized/darkblue = 35,
	/obj/item/slimecross/stabilized/silver = 35,
	/obj/item/slimecross/stabilized/red = 32,
	/obj/item/slimecross/stabilized/green = 32,
	/obj/item/slimecross/stabilized/pink = 30,
	/obj/item/slimecross/stabilized/lightpink = 25,
	/obj/item/slimecross/stabilized/black = 25,
	/obj/item/slimecross/stabilized/oil = 25,
	/obj/item/slimecross/stabilized/adamantine = 22,
	/obj/item/slimecross/stabilized/pyrite = 22,
	/obj/item/slimecross/stabilized/cerulean = 22,
	/obj/item/slimecross/stabilized/sepia = 22,
	/obj/item/slimecross/stabilized/bluespace = 18,
	/obj/item/slimecross/stabilized/gold = 15,
	/obj/item/slimecross/stabilized/rainbow = 10,

	// ========== CROSSBREEDS: CHARGED (ВЕСА 45-10) ==========
	/obj/item/slimecross/charged/grey = 45,
	/obj/item/slimecross/charged/orange = 45,
	/obj/item/slimecross/charged/purple = 42,
	/obj/item/slimecross/charged/blue = 42,
	/obj/item/slimecross/charged/metal = 42,
	/obj/item/slimecross/charged/yellow = 40,
	/obj/item/slimecross/charged/darkpurple = 35,
	/obj/item/slimecross/charged/darkblue = 35,
	/obj/item/slimecross/charged/silver = 35,
	/obj/item/slimecross/charged/red = 32,
	/obj/item/slimecross/charged/green = 32,
	/obj/item/slimecross/charged/pink = 30,
	/obj/item/slimecross/charged/lightpink = 25,
	/obj/item/slimecross/charged/black = 25,
	/obj/item/slimecross/charged/oil = 25,
	/obj/item/slimecross/charged/adamantine = 22,
	/obj/item/slimecross/charged/pyrite = 22,
	/obj/item/slimecross/charged/cerulean = 22,
	/obj/item/slimecross/charged/sepia = 22,
	/obj/item/slimecross/charged/bluespace = 18,
	/obj/item/slimecross/charged/gold = 15,
	/obj/item/slimecross/charged/rainbow = 10,
))
