/obj/machinery/vending/security
	products = list(
		/obj/item/restraints/handcuffs = 8,
		/obj/item/restraints/handcuffs/cable/zipties = 12,
		/obj/item/grenade/flashbang = 6,
		/obj/item/assembly/flash/handheld = 8,
		/obj/item/food/donut/plain = 12,
		/obj/item/storage/box/evidence = 6,
		/obj/item/flashlight/seclite = 6,
		/obj/item/restraints/legcuffs/bola/energy = 10,
		/obj/item/clothing/gloves/tackler/security = 5,
		/obj/item/gun/energy/e_gun/advtaser = 3,
	)
	contraband = list(
		/obj/item/clothing/glasses/sunglasses = 2,
		/obj/item/storage/fancy/donut_box = 2,
		/obj/item/melee/baton/security/stun_gun/stun_knife = 3,
	)
	premium = list(
		/obj/item/storage/belt/security/webbing = 5,
		/obj/item/storage/belt/security/webbing/peacekeeper = 5,
		/obj/item/coin/antagtoken = 1,
		/obj/item/clothing/head/helmet/blueshirt = 3,
		/obj/item/clothing/suit/armor/vest/blueshirt = 3,
		/obj/item/grenade/stingbang = 5,
		/obj/item/watertank/pepperspray = 2,
		/obj/item/storage/belt/holster/energy = 4,
		/obj/item/storage/box/holobadge = 1,
	)

/obj/machinery/vending/wardrobe/sec_wardrobe
	product_categories = list(
		list(
			"name" = "Main",
			"icon" = "shield", //curate these
			"products" = list(
				/obj/item/clothing/head/beret/sec = 5,
				/obj/item/clothing/head/soft/sec = 10,
				/obj/item/clothing/mask/bandana/striped/security = 5,
				/obj/item/clothing/under/rank/security/officer = 5,
				/obj/item/clothing/under/rank/security/officer/skirt = 5,
				/obj/item/clothing/under/rank/security/officer/grey = 5,
				/obj/item/clothing/under/pants/slacks = 5,
				/obj/item/clothing/under/rank/security/officer/blueshirt = 5,
				/obj/item/clothing/gloves/color/black/security/blu = 5,
				/obj/item/clothing/suit/armor/vest/secjacket = 5,
				/obj/item/clothing/suit/hooded/wintercoat/security = 5,
				/obj/item/clothing/suit/armor/vest = 5,
				/obj/item/clothing/suit/toggle/jacket/sec = 5,
				/obj/item/clothing/gloves/color/black/security = 5,
				/obj/item/clothing/shoes/jackboots/sec = 5,
				/obj/item/storage/backpack/security = 5,
				/obj/item/storage/backpack/satchel/sec = 5,
				/obj/item/storage/backpack/duffelbag/sec = 5,
				/obj/item/storage/backpack/messenger/sec = 5,
			),
		),
		list(
			"name" = "Alternate",
			"icon" = "shield-halved",
			"products" = list(
				/obj/item/clothing/head/beret/sec/nova = 5,
				/obj/item/clothing/head/security_cap = 10,
				/obj/item/clothing/suit/hooded/wintercoat/security/blue = 5,
				/obj/item/clothing/suit/toggle/jacket/sec/blue = 5,
				/obj/item/clothing/suit/armor/vest/peacekeeper/brit = 5,
				/obj/item/clothing/suit/armor/vest/peacekeeper/jacket = 5,
				/obj/item/clothing/suit/armor/vest/peacekeeper/jacket/badge = 5,
				/obj/item/clothing/neck/security_cape = 5,
				/obj/item/clothing/neck/security_cape/armplate = 5,
				/obj/item/storage/backpack/security = 5,
				/obj/item/storage/backpack/satchel/sec = 5,
				/obj/item/storage/backpack/duffelbag/sec = 5,
				/obj/item/storage/backpack/duffelbag/sec = 5,
				/obj/item/clothing/under/rank/security/officer = 10,
				/obj/item/clothing/under/rank/security/officer/skirt = 10,
				/obj/item/clothing/under/rank/security/peacekeeper/dress = 10,
				/obj/item/clothing/under/rank/security/peacekeeper/plain_skirt = 10,
				/obj/item/clothing/under/rank/security/peacekeeper/miniskirt = 10,
				/obj/item/clothing/under/rank/security/peacekeeper/jumpsuit = 10,
				/obj/item/clothing/under/rank/security/peacekeeper = 10,
				/obj/item/clothing/under/rank/security/nova/utility/blue = 3,
				/obj/item/clothing/under/rank/security/trousers = 10,
				/obj/item/clothing/under/rank/security/trousers/shorts = 10,
				/obj/item/clothing/shoes/jackboots/sec = 10,
				/obj/item/clothing/head/security_garrison = 10,
				/obj/item/clothing/head/helmet/sec/sol = 5,
				/obj/item/clothing/head/hats/warden/police/patrol = 5,
				/obj/item/clothing/head/costume/ushanka/sec = 10,
				/obj/item/clothing/gloves/color/black/security = 10,
			),
		),
	premium = list(
		/obj/item/clothing/under/rank/security/officer/formal = 3,
		/obj/item/clothing/suit/jacket/officer/blue = 3,
		/obj/item/clothing/head/beret/sec/navyofficer = 3,
		/obj/item/riding_saddle/leather/leather = 3,
			/obj/item/riding_saddle/leather/leather/blue = 2,
		),
	)
	payment_department = ACCOUNT_SEC
	light_color = COLOR_MODERATE_BLUE
