/mob/living/basic/trader/burger
	name = "Mc Bruce the chef"
	desc = "A food merchant who wishes to sell you food! why do they have a pulse pistol...?"
	unique_name = FALSE
	icon = 'icons/mob/simple/simple_human.dmi'
	maxHealth = 200
	health = 200
	melee_damage_lower = 10
	melee_damage_upper = 10
	attack_verb_continuous = "punches"
	attack_verb_simple = "punch"
	attack_sound = 'sound/items/weapons/punch1.ogg'
	basic_mob_flags = DEL_ON_DEATH
	unsuitable_atmos_damage = 2.5
	combat_mode = FALSE
	move_resist = MOVE_FORCE_STRONG
	mob_biotypes = MOB_ORGANIC|MOB_HUMANOID
	sentience_type = SENTIENCE_HUMANOID
	speed = 0
	ai_controller = /datum/ai_controller/basic_controller/trader
	sell_sound = 'sound/effects/cashregister.ogg'
	currency_name = "credits"
	spawner_path = /obj/effect/mob_spawn/corpse/human/cargo_tech
	species_path = /datum/species/human
	loot = list(/obj/effect/mob_spawn/corpse/human)
	ranged_attack_casing = /obj/item/ammo_casing/energy/laser/pulse
	ranged_attack_sound = 'sound/items/weapons/gun/pistol/shot.ogg'
	held_weapon_visual = /obj/item/gun/energy/pulse/pistol
	trader_data_path = /datum/trader_data/burger_trader_data
