/obj/machinery/vending/autodrobe
	product_categories_nova = list(
		list(
			"name" = "Costumes",
			"icon" = "mask",
			"products" = list(
				/obj/item/clothing/under/costume/nova/cavalry = 5,
				/obj/item/clothing/under/doug_dimmadome = 5,
				/obj/item/clothing/head/costume/kabuto = 5,
				/obj/item/clothing/suit/costume/samurai = 5,
				/obj/item/clothing/suit/dutchjacketsr = 5,
				/obj/item/clothing/head/costume/sombrero = 5,
				/obj/item/clothing/head/playbunnyears = 6,
				/obj/item/clothing/head/playbunnyears/british = 6,
				/obj/item/clothing/head/playbunnyears/communist = 6,
				/obj/item/clothing/head/playbunnyears/usa = 6,
				/obj/item/clothing/neck/tie/bunnytie = 6,
				/obj/item/clothing/neck/tie/bunnytie/blue = 6,
				/obj/item/clothing/neck/tie/bunnytie/communist = 6,
				/obj/item/clothing/neck/tie/bunnytie/magician = 6,
				/obj/item/clothing/suit/jacket/tailcoat = 6,
				/obj/item/clothing/suit/jacket/tailcoat/british = 6,
				/obj/item/clothing/suit/jacket/tailcoat/communist = 6,
				/obj/item/clothing/suit/jacket/tailcoat/magician = 6,
				/obj/item/clothing/suit/jacket/tailcoat/plasmaman = 6,
				/obj/item/clothing/suit/jacket/tailcoat/usa = 6,
				/obj/item/clothing/under/costume/playbunny/british = 6,
				/obj/item/clothing/under/costume/playbunny/communist = 6,
				/obj/item/clothing/under/costume/playbunny/greyscale = 6,
				/obj/item/clothing/under/costume/playbunny/magician = 6,
				/obj/item/clothing/under/costume/playbunny/usa = 6,
			),
		),
		list(
			"name" = "Entertainers",
			"icon" = "masks-theater",
			"products" = list(
				/obj/item/clothing/mask/gas/clownbald = 1,
				/obj/item/clothing/mask/gas/clown_colourable = 1,
				/obj/item/clothing/head/costume/jesteralt = 1,
				/obj/item/clothing/mask/gas/pink_clown_wig = 5,
				/obj/item/clothing/head/beret/clown = 5,
				/obj/item/clothing/under/rank/civilian/clown/jesteralt = 1,
				/obj/item/clothing/under/rank/civilian/clown/pink_clown_outfit = 5,
				/obj/item/clothing/shoes/clown_shoes/pink/heels = 5,
				/obj/item/clothing/gloves/pink_clown = 5,
				/obj/item/clothing/head/playbunnyears/clown = 3,
				/obj/item/clothing/head/playbunnyears/mime = 3,
				/obj/item/clothing/neck/tie/clown = 3,
				/obj/item/clothing/shoes/clown_shoes/heeled = 3,
				/obj/item/clothing/suit/jacket/tailcoat/clown = 3,
				/obj/item/clothing/suit/jacket/tailcoat/mime = 3,
				/obj/item/clothing/under/rank/civilian/clown/clown_bunnysuit = 3,
				/obj/item/clothing/under/rank/civilian/mime_bunnysuit = 3,
			),
		),
		list(
			"name" = "Fancy",
			"icon" = "user-tie",
			"products" = list(
				/obj/item/clothing/under/pants/nova/vicvest = 5,
				/obj/item/clothing/under/costume/nova/kamishimo = 5,
				/obj/item/clothing/under/costume/nova/yukata = 5,
				/obj/item/clothing/under/costume/nova/kimono = 5,
				/obj/item/clothing/under/costume/nova/shihakusho = 5,
				/obj/item/clothing/head/beret/badge = 5,
				/obj/item/clothing/mask/masquerade = 25,
				/obj/item/clothing/mask/masquerade/two_colors = 25,
				/obj/item/clothing/mask/masquerade/feathered = 25,
				/obj/item/clothing/mask/masquerade/two_colors/feathered = 25,
				/obj/item/clothing/neck/greyscaled = 5,
				/obj/item/clothing/neck/greyscaled/seecloak = 5,
				/obj/item/clothing/neck/greyscaled/matroncloak = 5,
				/obj/item/clothing/neck/greyscaled/xylixcloak = 5,
			),
		),
		list(
			"name" = "Service",
			"icon" = "kitchen-set",
			"products" = list(
				/obj/item/clothing/under/costume/buttondown/slacks/service = 1,
				/obj/item/clothing/under/costume/buttondown/skirt/service = 1,
				/obj/item/clothing/neck/bowtie = 2,
				/obj/item/clothing/accessory/waistcoat = 1,
				/obj/item/clothing/under/suit/waiter = 1,
				/obj/item/clothing/suit/apron = 1,
				/obj/item/clothing/suit/apron/overalls = 1,
				/obj/item/clothing/head/costume/maid_headband = 1,
				/obj/item/clothing/under/costume/maid = 1,
				/obj/item/clothing/under/rank/civilian/janitor/maid = 1,
				/obj/item/clothing/accessory/maidapron = 1,
				/obj/item/clothing/gloves/maid_arm_covers = 1,
				/obj/item/clothing/neck/maid_neck_cover = 1,
				/obj/item/clothing/under/maid_costume = 1,
				/obj/item/clothing/head/maid_headband = 1,
			),
		),
		list(
			"name" = "Other",
			"icon" = "star",
			"products" = list(
				/obj/item/clothing/glasses/biker = 5,
				/obj/item/clothing/suit/trenchblack = 5,
				/obj/item/clothing/suit/trenchbrown = 5,
				/obj/item/clothing/under/costume/nova/christmas = 5,
				/obj/item/clothing/under/costume/nova/christmas/croptop = 5,
				/obj/item/clothing/suit/hooded/wintercoat/nova/christmas = 5,
				/obj/item/clothing/suit/hooded/wintercoat/nova/christmas/green = 5,
				/obj/item/clothing/shoes/winterboots/christmas = 5,
				/obj/item/clothing/under/pants/tactical = 5,
				/obj/item/clothing/head/costume/santa/gags = 5,
			),
		),
	)

	contraband_nova = list(
		/obj/item/clothing/mask/balaclava/adjustable = 5,
		/obj/item/clothing/mask/balaclava/threehole = 5,
		/obj/item/clothing/mask/balaclava/threehole/green = 5,
		/obj/item/clothing/head/hats/imperial = 5,
		/obj/item/clothing/under/imperial = 5,
		/obj/item/clothing/under/imperialskirt = 5,
		/obj/item/clothing/head/costume/maid_headband/syndicate/loadout_headband = 5,
		/obj/item/clothing/gloves/tactical_maid = 5,
		/obj/item/clothing/under/syndicate/nova/maid/loadout_maid = 5,
		/obj/item/clothing/accessory/maidcorset/syndicate/loadout_corset = 5,
		/obj/item/clothing/head/playbunnyears/syndicate/fake = 3,
		/obj/item/clothing/neck/tie/bunnytie/syndicate = 3, //Armored but it's only Fire and Acid, not a balance concern
		/obj/item/clothing/suit/jacket/tailcoat/syndicate/fake = 3,
		/obj/item/clothing/under/syndicate/syndibunny/fake = 3,
	)

	premium_nova = list(
		/obj/item/clothing/under/dress/wedding_dress/ribbon = 1,
	)
