/obj/machinery/vending/autodrobe
	product_categories_nova = list(
		list(
			"name" = "Costumes",
			"icon" = "mask",
			"products" = list(
				/obj/item/clothing/under/costume/nova/cavalry = 5,
				/obj/item/clothing/under/doug_dimmadome = 5,
				/obj/item/clothing/head/costume/kabuto = 5,
				/obj/item/clothing/suit/costume/samurai = 5,
				/obj/item/clothing/suit/dutchjacketsr = 5,
				/obj/item/clothing/head/costume/sombrero = 5,
			),
		),
		list(
			"name" = "Entertainers",
			"icon" = "masks-theater",
			"products" = list(
				/obj/item/clothing/mask/gas/clownbald = 1,
				/obj/item/clothing/mask/gas/clown_colourable = 1,
				/obj/item/clothing/head/costume/jesteralt = 1,
				/obj/item/clothing/under/rank/civilian/clown/jesteralt = 1,
			),
		),
		list(
			"name" = "Fancy",
			"icon" = "user-tie",
			"products" = list(
				/obj/item/clothing/under/pants/nova/vicvest = 5,
				/obj/item/clothing/under/costume/nova/kamishimo = 5,
				/obj/item/clothing/under/costume/nova/yukata = 5,
				/obj/item/clothing/under/costume/nova/kimono = 5,
				/obj/item/clothing/head/beret/badge = 5,
				/obj/item/clothing/mask/masquerade = 25,
				/obj/item/clothing/mask/masquerade/two_colors = 25,
				/obj/item/clothing/mask/masquerade/feathered = 25,
				/obj/item/clothing/mask/masquerade/two_colors/feathered = 25,
			),
		),
		list(
			"name" = "Service",
			"icon" = "kitchen-set",
			"products" = list(
				/obj/item/clothing/under/costume/buttondown/slacks/service = 1,
				/obj/item/clothing/under/costume/buttondown/skirt/service = 1,
				/obj/item/clothing/neck/bowtie = 2,
				/obj/item/clothing/accessory/waistcoat = 1,
				/obj/item/clothing/under/suit/waiter = 1,
				/obj/item/clothing/suit/apron = 1,
				/obj/item/clothing/suit/apron/overalls = 1,
				/obj/item/clothing/head/costume/maidheadband = 1,
				/obj/item/clothing/under/costume/maid = 1,
				/obj/item/clothing/gloves/maid = 1,
				/obj/item/clothing/neck/maid = 1,
				/obj/item/clothing/under/rank/civilian/janitor/maid = 1,
				/obj/item/clothing/accessory/maidapron = 1,
				/obj/item/clothing/gloves/maid_arm_covers = 1,
				/obj/item/clothing/neck/maid_neck_cover = 1,
				/obj/item/clothing/under/maid_costume = 1,
				/obj/item/clothing/head/maid_headband = 1,
			),
		),
		list(
			"name" = "Other",
			"icon" = "star",
			"products" = list(
				/obj/item/clothing/glasses/biker = 5,
				/obj/item/clothing/suit/trenchblack = 5,
				/obj/item/clothing/suit/trenchbrown = 5,
				/obj/item/clothing/head/costume/nova/christmas = 5,
				/obj/item/clothing/head/costume/nova/christmas/green =  5,
				/obj/item/clothing/under/costume/nova/christmas = 5,
				/obj/item/clothing/under/costume/nova/christmas/green = 5,
				/obj/item/clothing/under/costume/nova/christmas/croptop = 5,
				/obj/item/clothing/under/costume/nova/christmas/croptop/green = 5,
				/obj/item/clothing/suit/hooded/wintercoat/nova/christmas = 5,
				/obj/item/clothing/suit/hooded/wintercoat/nova/christmas/green = 5,
				/obj/item/clothing/shoes/winterboots/christmas = 5,
				/obj/item/clothing/shoes/winterboots/christmas/green = 5,
				/obj/item/clothing/under/pants/tactical = 5,
			),
		),
	)

	contraband_nova = list(
		/obj/item/clothing/mask/balaclavaadjust = 5,
		/obj/item/clothing/mask/balaclava/threehole = 5,
		/obj/item/clothing/mask/balaclava/threehole/green = 5,
		/obj/item/clothing/head/hats/imperial/helmet = 5,
		/obj/item/clothing/head/hats/imperial/red = 5,
		/obj/item/clothing/head/hats/imperial/grey = 5,
		/obj/item/clothing/head/hats/imperial = 5,
		/obj/item/clothing/under/rank/captain/nova/imperial/generic/pants = 5,
		/obj/item/clothing/under/rank/captain/nova/imperial/generic/red = 5,
		/obj/item/clothing/under/rank/captain/nova/imperial/generic/grey = 5,
		/obj/item/clothing/under/rank/captain/nova/imperial/generic = 5,
	)
