/obj/machinery/vending/clothing
	product_categories_nova = list(
		list(
			"name" = "Head",
			"icon" = "hat-cowboy",
			"products" = list(
				/obj/item/clothing/head/beret/badge = 5,
				/obj/item/clothing/head/colourable_flatcap= 5,
				/obj/item/clothing/head/cowboy/nova/cattleman = 5,
				/obj/item/clothing/head/cowboy/nova/cattleman/wide = 5,
				/obj/item/clothing/head/cowboy/nova/wide = 5,
				/obj/item/clothing/head/cowboy/nova/wide/feathered = 5,
				/obj/item/clothing/head/cowboy/nova/flat = 5,
				/obj/item/clothing/head/cowboy/nova/flat/cowl = 5,
				/obj/item/clothing/head/cowboy/nova/flat/sheriff = 5,
				/obj/item/clothing/head/cowboy/nova/flat/deputy = 5,
				/obj/item/clothing/head/cowboy/nova/flat/cowl/sheriff = 5,
				/obj/item/clothing/head/fedora= 5,
				/obj/item/clothing/head/fedora/brown = 5,
				/obj/item/clothing/head/fedora/beige = 5,
				/obj/item/clothing/head/fedora/white = 5,
				/obj/item/clothing/head/standalone_hood = 5,
				/obj/item/clothing/head/small_bow = 5,
				/obj/item/clothing/head/large_bow = 5,
				/obj/item/clothing/head/back_bow = 5,
				/obj/item/clothing/head/sweet_bow = 5,
			),
		),

		list(
			"name" = "Accessories",
			"icon" = "glasses",
			"products" = list(
				/obj/item/clothing/neck/ranger_poncho = 5,
				/obj/item/clothing/neck/cloak/colourable = 5,
				/obj/item/clothing/neck/cloak/colourable/veil = 5,
				/obj/item/clothing/neck/cloak/colourable/shroud = 5,
				/obj/item/clothing/neck/cloak/colourable/boat = 5,
				/obj/item/clothing/neck/mantle/recolorable = 5,
				/obj/item/clothing/neck/tesharian_mantle = 5,
				/obj/item/clothing/neck/long_cape = 5,
				/obj/item/clothing/neck/wide_cape = 5,
				/obj/item/clothing/neck/robe_cape = 5,
				/obj/item/clothing/glasses/regular/betterunshit = 5,
				/obj/item/clothing/glasses/thin = 5,
				/obj/item/clothing/glasses/hud/ar/projector = 5,
				/obj/item/clothing/neck/face_scarf = 5,
				/obj/item/clothing/mask/neck_gaiter = 5,
				/obj/item/clothing/gloves/bracer/wraps = 5,
			),
		),

		list(
			"name" = "Under",
			"icon" = "shirt",
			"products" = list(
				/obj/item/clothing/under/pants/nova/jeans_ripped = 5,
				/obj/item/clothing/under/pants/nova/loose_pants = 5,
				/obj/item/clothing/under/pants/nova/big_pants = 5,
				/obj/item/clothing/under/dress/skirt/nova/loincloth = 5,
				/obj/item/clothing/under/dress/skirt/nova/loincloth/loincloth_alt = 5,
				/obj/item/clothing/under/shorts/nova/shorts_ripped = 5,
				/obj/item/clothing/under/pants/nova/yoga = 5,
				/obj/item/clothing/under/misc/nova/mechanic = 5,
				/obj/item/clothing/under/misc/bluetracksuit = 5,
				/obj/item/clothing/under/suit/nova/recolorable = 5,
				/obj/item/clothing/under/suit/nova/recolorable/skirt = 5,
				/obj/item/clothing/under/pants/nova/kilt = 5,
				/obj/item/clothing/under/suit/fancy = 5,
				/obj/item/clothing/under/texas = 5,
				/obj/item/clothing/under/sweater = 5,
				/obj/item/clothing/under/sweater/keyhole = 5,
				/obj/item/clothing/under/tachawaiian = 5,
				/obj/item/clothing/under/tachawaiian/purple = 5,
				/obj/item/clothing/under/tachawaiian/green = 5,
				/obj/item/clothing/under/tachawaiian/blue = 5,
				/obj/item/clothing/under/suit/nova/black_really_collared = 3,
				/obj/item/clothing/under/suit/nova/black_really_collared/skirt = 3,
				/obj/item/clothing/under/suit/nova/pencil = 3,
				/obj/item/clothing/under/suit/nova/pencil/black_really = 3,
				/obj/item/clothing/under/suit/nova/pencil/charcoal = 3,
				/obj/item/clothing/under/suit/nova/pencil/navy = 3,
				/obj/item/clothing/under/suit/nova/pencil/burgandy = 3,
				/obj/item/clothing/under/suit/nova/pencil/checkered = 3,
				/obj/item/clothing/under/suit/nova/pencil/tan = 3,
				/obj/item/clothing/under/suit/nova/pencil/green = 3,
				/obj/item/clothing/under/suit/nova/inferno = 3,
				/obj/item/clothing/under/suit/nova/inferno/skirt = 3,
				/obj/item/clothing/under/suit/nova/helltaker = 3,
				/obj/item/clothing/under/suit/nova/helltaker/skirt = 3,
				/obj/item/clothing/under/dress/skirt/nova/medium = 5,
				/obj/item/clothing/under/dress/skirt/nova/long = 5,
				/obj/item/clothing/under/dress/nova/giant_scarf = 5,
			),
		),

		list(
			"name" = "Suits & Skirts",
			"icon" = "vest",
			"products" = list(
				/obj/item/clothing/under/dress/skirt/nova/lone_skirt = 5,
				/obj/item/clothing/under/dress/skirt/nova/turtleskirt_knit = 5,
				/obj/item/clothing/under/dress/nova/short_dress = 5,
				/obj/item/clothing/under/dress/nova/pinktutu = 5,
				/obj/item/clothing/under/dress/skirt/nova/jean = 5,
				/obj/item/clothing/under/dress/nova/flower = 5,
				/obj/item/clothing/under/dress/nova/strapless = 5,
				/obj/item/clothing/under/dress/nova/pentagram = 5,
				/obj/item/clothing/suit/varsity = 5,
				/obj/item/clothing/suit/toggle/jacket = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/gags = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/red = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/aqua = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/brown = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/trim = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/trim/alt = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/cti = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/mu = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/smw = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/nrti = 5,
				/obj/item/clothing/suit/toggle/jacket/cardigan = 5,
				/obj/item/clothing/suit/toggle/peacoat = 5,
				/obj/item/clothing/suit/toggle/trackjacket = 5,
				/obj/item/clothing/suit/toggle/lawyer/white = 5,
				/obj/item/clothing/suit/urban = 5,
				/obj/item/clothing/suit/duster = 5,
				/obj/item/clothing/suit/fallsparka = 5,
				/obj/item/clothing/suit/jacket/croptop = 5,
				/obj/item/clothing/suit/jacket/white_robe = 5,
				/obj/item/clothing/suit/modernwintercoatthing = 5,
				/obj/item/clothing/suit/hooded/wintercoat/colourable = 5,
				/obj/item/clothing/suit/apron/chef/colorable_apron = 5,
				/obj/item/clothing/suit/warm_coat = 5,
				/obj/item/clothing/suit/warm_sweater = 5,
				/obj/item/clothing/suit/heart_sweater = 5,
				/obj/item/clothing/suit/crop_jacket = 5,
				/obj/item/clothing/suit/crop_jacket/shortsleeve = 5,
				/obj/item/clothing/suit/crop_jacket/sleeveless = 5,
				/obj/item/clothing/suit/crop_jacket/long = 5,
				/obj/item/clothing/suit/crop_jacket/shortsleeve/long = 5,
				/obj/item/clothing/suit/crop_jacket/sleeveless/long = 5,
				/obj/item/clothing/suit/big_jacket = 5,
				/obj/item/clothing/suit/dagger_mantle = 5,
			),
		),

		list(
			"name" = "Shoes",
			"icon" = "socks",
			"products" = list(
				/obj/item/clothing/shoes/colorable_laceups = 5,
				/obj/item/clothing/shoes/colorable_sandals = 5,
				/obj/item/clothing/shoes/sports = 5,
				/obj/item/clothing/shoes/wraps/colourable = 5,
				/obj/item/clothing/shoes/wraps/cloth = 5,
				/obj/item/clothing/shoes/jungleboots = 5,
				/obj/item/clothing/shoes/jackboots/knee = 5,
				/obj/item/clothing/shoes/jackboots/recolorable = 5,
				/obj/item/clothing/shoes/jackboots/duckboots = 5,
			),
		),

		//Only put clothing in Special thats either Families or exteremly out-of-place
		list(
			"name" = "Special",
			"icon" = "star",
			"products" = list(
				/obj/item/clothing/under/costume/deckers/alt = 5,
				/obj/item/clothing/under/costume/nova/bathrobe = 5,
				/obj/item/clothing/mask/gas/respirator = 5,
				/obj/item/clothing/mask/surgical/greyscale = 5,
				/obj/item/clothing/glasses/blindfold/color = 5,
			)
		)
	)

	premium_nova = list( //being here means you're artificially rare, congratulations
		/obj/item/clothing/shoes/jackboots/timbs = 2,
		/obj/item/clothing/head/soft/yankee = 3,
		/obj/item/clothing/suit/brownbattlecoat = 1,
		/obj/item/clothing/suit/blackfurrich = 1,
		/obj/item/clothing/suit/frenchtrench = 1,
		/obj/item/clothing/suit/toggle/labcoat/nova/lalunevest = 2,
		/obj/item/clothing/gloves/lalune_long = 2,
		/obj/item/clothing/head/skrell_chain = 3,
		/obj/item/clothing/head/skrell_chain/silver = 3,
	)

	contraband_nova = list(
		/obj/item/clothing/mask/neck_gaiter/syndicate/tacticool = 2,
	)
