#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_CARGO "/Cargo Cyborgs"
#define RND_CATEGORY_MECHFAB_SYNTH "/Synth"
#define RND_SUBCATEGORY_MECHFAB_SYNTH_PARTS "/Bodyparts"

#define RND_CATEGORY_HC_FOOD "Provision"
#define RND_CATEGORY_HC_MEDICAL "Medicine"
#define RND_CATEGORY_HC_CLOTHING "Apparel"
