#define RIDING_TAUR (1<<10) // high, to avoid flag conflict with tg)

#define OVERSIZED_OFFSET 18
#define OVERSIZED_SIDE_OFFSET 11
#define REGULAR_OFFSET 6
#define REGULAR_SIDE_OFFSET 4
#define REGULAR_TAUR_OFFSET 8
#define REGULAR_TAUR_SIDE_OFFSET 6
#define REGULAR_TAUR_OVERSIZED_OFFSET 20
#define REGULAR_TAUR_SIDE_OVERSIZED_OFFSET 13
