name: 'New PR Notification'
on:
  pull_request_target:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "Check for DISCORD_WEBHOOK"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
      - name: Send Discord notification
        uses: tgstation/discord-notify@v3
        if: >
          steps.secrets_set.outputs.SECRETS_ENABLED &&
          (github.event.pull_request.merged == true || github.event.action == 'opened') &&
          github.event.pull_request.author_association != 'FIRST_TIMER' &&
          github.event.pull_request.author_association != 'FIRST_TIME_CONTRIBUTOR'
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          include_image: true
          avatar_url: https://raw.githubusercontent.com/tgstation/tgstation/refs/heads/master/icons/ui/common/tg_32.png
          username: GitHub
          title_url: "${{ github.event.pull_request.html_url }}"
